name: environment-dev

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - pip

  # Development tools
  - black=26.5.1
  - ruff=0.16.0
  - pre-commit
  - pytest
  - coverage
  - pyyaml
  - jupyter
  - nbstripout

  - pip:
      - "black[jupyter]==26.5.1"
