name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: envs/environment-dev.yml
          activate-environment: project-dev
          auto-activate-base: false
          channels: conda-forge,bioconda
          channel-priority: flexible

      - name: Install project
        shell: bash -el {0}
        run: pip install .

      - name: Run tests
        shell: bash -el {0}
        run: pytest